apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: volcano-monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ["instance"]
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 4h
      receiver: "feishu"
      routes:
        - match:
            severity: critical
          receiver: "feishu"
          continue: false
        - match:
            severity: warning
          receiver: "feishu"
          continue: false
        - match:
            process: aicloud
          receiver: "aicloud"
          repeat_interval: 10m
          continue: false
    receivers:
      - name: "feishu"
        webhook_configs:
          - url: "http://10.1.2.2:8808/webhook"
      - name: "aicloud"
        webhook_configs:
          - url: "http://venus-aicloud-backend-service.venus.svc:8081/api/v1/alertmanager/alerts"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: volcano-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: harbor.local.clusters/kubesphereio/alertmanager:latest
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --log.level=debug
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
            - name: tz-config
              mountPath: /etc/timezone
              readOnly: true
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: volcano-monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      nodePort: 30093
  selector:
    app: alertmanager