{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calico-felix.fullname" . }}
  labels:
    app: calico-felix
spec:
  type: {{ .Values.service.type }}
  selector:
    app: calico-felix
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
{{- end }}
