apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coredns
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: nodename
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'up|process_cpu_seconds_total|go_memstats_alloc_bytes|coredns_dns_requests_total|coredns_cache_requests_total|coredns_dns_responses_total'
          action: keep
