{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor-exporter.fullname" . }}
  labels:
    app: harbor-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      containers:
      - name: harbor-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: metrics
        resources: {{- toYaml .Values.resources | nindent 10 }}
{{- end }}
