{{- if .Values.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "postgres-exporter.fullname" . }}
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 15s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'pg_.*|up'
      action: keep
{{- end }}
