{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvidia-gpu-exporter.fullname" . }}
  labels:
    app: nvidia-gpu-exporter
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nvidia-gpu-exporter
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
{{- end }}
