apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gpu-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: nvidia-gpu-alerts
      rules:
        # GPU 设备指标阈值监控
        - alert: DCGM_Device_Metric_Threshold
          expr: count by (instance) (DCGM_FI_DEV_MEMORY_TEMP) < 8
          for: 30s
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0102"
          annotations:
            summary: "DCGM metrics < 8 on instance {{ $labels.instance }}"
            description: "GPU 异常：监控指标数量少于8个"
            ip: "{{ $labels.instance }}"

        # GPU XID 错误监控
        - alert: DCGM_XID_Errors
          expr: >-
            DCGM_FI_DEV_XID_ERRORS > 0 and
            DCGM_FI_DEV_XID_ERRORS{xid!~".*31.*"} > 0 and
            DCGM_FI_DEV_XID_ERRORS{xid!~".*43.*"} > 0
          for: 30s
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0107"
          annotations:
            summary: "XID Errors detected on instance {{ $labels.instance }}"
            description: "GPU {{ $labels.gpu }} (model {{ $labels.modelName }}) XID is {{ $value }}"
            ip: "{{ $labels.instance }}"

        # GPU ECC 双位错误监控
        - alert: GPUECCDoubleBitError
          expr: DCGM_FI_DEV_ECC_DBE_VOL_TOTAL > 0
          for: 30s
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0103"
          annotations:
            description: "GPU {{ $labels.gpu }} (model {{ $labels.modelName }}) has detected double bit ECC errors {{$value}}."
            summary: "GPU has double bit ECC errors, indicating a potential severe hardware failure."
            ip: "{{ $labels.instance }}"

        # GPU ECC 单位错误监控
        - alert: GPUECCSingleBitError
          expr: DCGM_FI_DEV_ECC_SBE_VOL_TOTAL > 0
          for: 2m
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0104"
          annotations:
            description: "GPU {{ $labels.gpu }} (model {{ $labels.modelName }}) has detected single bit ECC errors {{$value}}."
            summary: "GPU has single bit ECC errors, which may indicate a developing hardware failure."
            ip: "{{ $labels.instance }}"

        # GPU 功耗违规监控
        - alert: GPUPowerViolation
          expr: DCGM_FI_DEV_POWER_VIOLATION > 0
          for: 30s
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0105"
          annotations:
            description: "GPU {{ $labels.gpu }} (model {{ $labels.modelName }}) on node {{ $labels.Hostname }} has throttled due to power constraints."
            summary: "GPU is throttling due to power violation (over power limit).(slowdown)"
            ip: "{{ $labels.instance }}"

        # GPU 温度违规监控
        - alert: GPUTemperatureViolation
          expr: DCGM_FI_DEV_THERMAL_VIOLATION > 0
          for: 30s
          labels:
            severity: P2
            alert_type: "HARD_WARE"
            id: "GPU_0106"
          annotations:
            description: "GPU {{ $labels.gpu }} (model {{ $labels.modelName }}) on node {{ $labels.Hostname }} has throttled due to thermal constraints."
            summary: "GPU is throttling due to thermal violation (over temperature limit)."
            ip: "{{ $labels.instance }}"

        # GPU 显存温度过高监控
        - alert: HighMemoryTemperature
          expr: DCGM_FI_DEV_MEMORY_TEMP > 80
          for: 2m
          labels:
            severity: P2
            alert_type: "HARD_WARE"
            id: "GPU_0101"
          annotations:
            summary: "The memory temperature of device {{ $labels.device }} is too high ({{ $value }}°C)"
            description: "The memory temperature of device {{ $labels.device }} has exceeded 80°C for more than 2 minutes."
            ip: "{{ $labels.instance }}"

        # GPU 核心温度过高监控
        - alert: HighGPULoadTemperature
          expr: DCGM_FI_DEV_GPU_TEMP > 80
          for: 2m
          labels:
            severity: P2
            alert_type: "HARD_WARE"
            id: "GPU_0008"
          annotations:
            summary: "The GPU temperature of device {{ $labels.device }} is too high ({{ $value }}°C)"
            description: "The GPU temperature of device {{ $labels.device }} has exceeded 80°C for more than 2 minutes."
            ip: "{{ $labels.instance }}"

        # 掉卡监控
        - alert: GPUoffline
          expr: dcgm_exporter_last_scrape_error == 0 and absent(DCGM_FI_DEV_GPU_UTIL)
          for: 30s
          labels:
            severity: P1
            alert_type: "HARD_WARE"
            id: "GPU_0109"
          annotations:
            summary: "GPU {{ $labels.gpu }} 在节点 {{ $labels.instance }} 失联"
            description: "GPU {{ $labels.gpu }} 在节点 {{ $labels.instance }} 失联，可能是掉卡"

    - name: gpu-emergency-alerts
      rules:
        - alert: MultipleGPUNodesDown
          expr: count(up{job="nvidia-gpu-exporter"} == 0) > 3
          for: 30s
          labels:
            severity: P0
            alert_type: "HARD_WARE"
            id: "GPU_P0_001"
          annotations:
            summary: "多个GPU节点同时故障"
            description: "超过3个GPU节点同时不可用，当前故障节点数: {{ $value }}"
